require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  CountAsOne: [array, hash]
  Exclude:
    - "test/**/*"

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Metrics/CyclomaticComplexity:
  Max: 8

Lint/MissingSuper:
  Enabled: false
